### ISSUE TITLE
Index for C2

### ISSUE THREAD

**Issue by dentarthur** [Maksakovsky-admin/technical#16]
See https://github.com/thecapitalistcycle/reproduction-schemes/blob/master/capital-ebooks.md

Please get C2 and use Calibre to convert to html and provide link to the htmls with general index.

Need to look at it to see how to import into indexing software for comparison.

Will want to start indexing project with C2 as more directly relevant to other work for Maksakovsky.

Also please do the ToDo for C4 at above link.

**Comment by DavidMc1948** [comment]
[C2 html](https://davidmc1948.github.io/C2%20HTML/index.html)
